# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
orbs: # declare what orbs we are going to use
  node: circleci/node@4.1.0 # the node orb provides common node-related configuration 

package:
  exclude:
  - coverage/**
  - .circleci/**


version: 2.1


workflows:
  development:
    jobs:
      - build:
          context:
            - ccits
      - performance:
          requires:
            - build
          context:
            - ccits
          filters:
            branches:
              only: /stress(?:-.+)?$/
jobs:
  build:
    working_directory: ~/app
    # specify the version you desire here
    docker:
      - image: cimg/node:15.2.0

    steps:
      - checkout
      - run: node --version
      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-cache

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            sudo npm i -g typescript
            npm install
            
      # deploy app            
      - run:
          name: Deploy application 
          command: sls deploy -v

      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}
  performance:
      docker:
        # specify the version you desire here
        - image: cimg/node:15.2.0
      steps:
        - checkout
        - run:
            name: Install Artillery CLI
            command: |
              sudo npm install -g artillery
              sudo npm install -g artillery-plugin-faker
        - run: artillery dino
        - run: artillery run ./load.yml